
---
## Author
author:
  name: Арбатова Варвара Петровна, Карпова Есения Алексеевна, Дагделен Зейнап Реджеповна, Бюгданюк Анна Васильевна, Люпп Софья Романовна
  degrees: DSc
  orcid: 0000-0002-0877-7063
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Орджоникидзе 3
## Title
title: "Образование Солнечной системы"
subtitle: "Теоретические основы"
license: CC BY
date: today
date-format: "YYYY-MM-DD"
---

# Введение

## Цель и задачи работы

- Подвести итог выполненной проектной работы
- Обобщить теоретические, алгоритмические и программные результаты
- Провести коллективное обсуждение достигнутого
- Оценить вклад каждого участника и определить перспективы развития модели.

# Что сделано в рамках проектной работы

## Теоретическое исследование

Выведены и обоснованы математические соотношения:

- Гравитационный потенциал системы частиц
- Начальные условия для равномерного распределения в диске с кеплеровскими скоростями
- Силы отталкивания при контакте (закон степени 8)
- Силы трения, зависящие от относительной тангенциальной скорости
- Уравнения вращения частиц и момент инерции
- Условие слипания с сохранением массы, импульса и вычислением радиуса новой частицы

## Разработка алгоритмов

Разработан главный цикл моделирования, включающий:

- Вычисление всех парных сил (гравитация всегда, отталкивание и трение только при контакте)
- Интегрирование уравнений движения методом Верле (скоростная форма, второй порядок точности)
- Ибновление угловых скоростей на основе моментов сил трения
- Ироверку условия слипания и объединения частиц
- Расчёт кинетической (поступательной и вращательной), потенциальной и полной энергии, а также энергии, перешедшей в тепло


## Программная реализация

- `particle.jl` – определение типа `Particle`, функции слияния, вычисления энергий, обнуления импульса
- `forces.jl` – вычисление гравитационных сил, сил отталкивания, трения и моментов
- `integrator.jl` – метод Верле и шаг по времени
- `simulation.jl` – генерация начальных условий (2D/3D диски, разные массы, случайные параметры)
- `visualization.jl` – построение проекций, графиков энергий, числа частиц, траекторий, анимация
- `main.jl` и `quickrun.jl` – запуск всех заданий

## Полученные результаты и их интерпретация

Получены графики:

- зависимость кинетической
- потенциальной, полной энергии и тепловых потерь от времени
- проекции движения частиц
- эволюция числа активных частиц

## Коллективное обсуждение результатов

В ходе совместной работы мы обсудили следующие аспекты:

- достоинства модели
- ограничения и допущения
- сложности при реализации
- что удалось достичь
- пути улучшения

## Самооценка деятельности

- Арбатова В.П. – руководитель группы
- Карпова Е.А. – написание документации
- Дагделен З.Р. – создание модуля визуализации
- Бюгданюк А.В. – генерация начальных условий
- Люпп С.Р. – разработка алгоритмов вычисления сил и интеграции,

# Выводы

1. Создана численная модель образования планет с гравитацией, трением и слипанием.
2. Модель воспроизводит эволюцию от хаоса частиц до крупных тел.
3. Освоены навыки: Julia, симуляции, визуализация, командная работа.
